### PR TITLE
First changes in view of Fractal V2

### LINKED ISSUE #7: test_valid_manifest fails after fractal-server refactor
Hi,

I noticed a few days back that my test_valid_manifest test that my fractal task package inherited from fractal-tasks-template started to fail. I suspect it has to do with the refactor of fractal-server.

I got the following error message:

```
======================================================================================================================================================================================================== FAILURES ========================================================================================================================================================================================================
__________________________________________________________________________________________________________________________________________________________________________________________________ test_valid_manifest ___________________________________________________________________________________________________________________________________________________________________________________________________

tmp_path = PosixPath('/tmp/pytest-of-atschan/pytest-565/test_valid_manifest0')

    def test_valid_manifest(tmp_path):
        """
        NOTE: to avoid adding a fractal-server dependency, we simply download the
        relevant file.
        """
        # Download JSON Schema for ManifestV1
        url = (
            "https://raw.githubusercontent.com/fractal-analytics-platform/"
            "fractal-server/main/"
            "fractal_server/app/schemas/json_schemas/manifest.json"
        )
        r = requests.get(url)
        with (tmp_path / "manifest_schema.json").open("wb") as f:
            f.write(r.content)
        with (tmp_path / "manifest_schema.json").open("r") as f:
>           manifest_schema = json.load(f)

tests/test_valid_manifest.py:24:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/json/__init__.py:293: in load
    return loads(fp.read(),
/data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/json/__init__.py:346: in loads
    return _default_decoder.decode(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7fa5825bd180>, s = '404: Not Found', _w = <built-in method match of re.Pattern object at 0x7fa582521560>

    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` instance
        containing a JSON document).

        """
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        end = _w(s, end).end()
        if end != len(s):
>           raise JSONDecodeError("Extra data", s, end)
E           json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

/data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/json/decoder.py:340: JSONDecodeError
==================================================================================================================================================================================================== warnings summary ====================================================================================================================================================================================================
../../../../../../../../../../data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/site-packages/skimage/util/dtype.py:27
  /data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
    np.bool8: (False, True),

../../../../../../../../../../data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/site-packages/phenograph/cluster.py:13
  /data/homes/atschan/.conda/envs/fractal_tasks_core_0.14.2/lib/python3.10/site-packages/phenograph/cluster.py:13: DeprecationWarning: Please import `spmatrix` from the `scipy.sparse` namespace; the `scipy.sparse.base` namespace is deprecated and will be removed in SciPy 2.0.0.
    from scipy.sparse.base import spmatrix

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================================================================================================================================ short test summary info =================================================================================================================================================================================================
FAILED tests/test_valid_manifest.py::test_valid_manifest - json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
====================================================================================================================================================================================== 1 failed, 50 deselected, 2 warnings in 6.14s ======================================================================================================================================================================================
```

Looks like the url to the fractal manifest json file on fractal-server has changed recently. I had to update the url to fix the problem:

```python
def test_valid_manifest(tmp_path):
    """
    NOTE: to avoid adding a fractal-server dependency, we simply download the
    relevant file.
    """
    # Download JSON Schema for ManifestV1
    url = (
        "https://raw.githubusercontent.com/fractal-analytics-platform/"
        "fractal-server/main/"
        "fractal_server/json_schemas/manifest_v1.json"
    )
    r = requests.get(url)
    with (tmp_path / "manifest_schema.json").open("wb") as f:
        f.write(r.content)
    with (tmp_path / "manifest_schema.json").open("r") as f:
        manifest_schema = json.load(f)

    debug(MANIFEST)
    validate(instance=MANIFEST, schema=manifest_schema)
```

Just a heads up :smiley:

### PR DESCRIPTION
**Pull request by tcompa**
Close #7

### CODE REVIEW

**Comment by tcompa** [comment]
Useful command for testing
```
copier copy gh:fractal-analytics-platform/fractal-tasks-template your-package-name --vcs-ref=v2
```

**Comment by tcompa** [comment]
The template now comes with a GitHub action that runs this script:
```bash
#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Create empty folder (fail if it already exists)
FOLDER="/tmp/new-project-folder"

# Generate a new project based on the HEAD git reference
echo "Now generate a new project copy in $FOLDER"
copier copy . "$FOLDER" --data-file tests/answers.yml --vcs-ref=HEAD

# Move to the new folder
cd "$FOLDER"

# Install the new project
python3 -m pip install -e .[dev]

# Generate the manifest
python3 src/my_project/dev/create_manifest.py

# Run tests
python3 -m pytest tests
```

**Comment by jluethi** [comment]
Just for my understanding: This script checks that the manifest can be build & that the tests run?

**Comment by jluethi** [comment]
Or is the validity of the manifest tested with that?

**Comment by tcompa** [comment]
The script simulates what a new task developer would do:
1. Create a new project based on the current template (this may catch errors in the template, if we change in the future)
2. Install the new project (this may catch errors in pyproject.toml, e.g. if we require an invalid fractal-tasks-core version)
3. Create new manifest (this may catch errors e.g. if we write a new task but we do not correctly set up its call signature, or the function name..)
4. Run tests (this may catch errors e.g. when we add a test for the new task)


Caveat: this flow differs from what a user would face, because it uses the current HEAD from git (which is useful so that we can run it from the PR branch). Note that the actual usage of `copier` by default pulls the latest git tag (rather than `main` or a specific HEAD).

**Comment by tcompa** [comment]
I now added:

5. Performs the build of the package

**Pull request merged**
